services:
  backend:
    build:
      context: .
      dockerfile: backend_py/Dockerfile
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./certs:/app/certs
    command: sh /app/backend_py/entrypoint.sh
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - FRONTEND_ORIGIN=*
      - USE_MQTT=false
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
      - MQTT_TOPIC=yolo/crosswalk/cam-001
      - LAN_IP=192.168.1.35
      - YOLO_MODEL_PATH=yolov8n.pt
      - YOLO_CONF=0.35
      - BILLBOARD_MODE=true
      - RTSP_CAMERA_ENABLE=true
      - RTSP_CAMERA_USER=admin
      - RTSP_CAMERA_PASS=12345
      - RTSP_CAMERA_IP=192.168.1.76
      - RTSP_CAMERA_PORT=554
      - RTSP_CAMERA_PATH=/live/ch0
      - RTSP_CAMERA_URL=rtsp://go2rtc:8554/vta_camera
      - TUYA_CLIENT_ID=3a8cs4wmgppk54p9pkvv
      - TUYA_CLIENT_SECRET=8c7656d031a544a19461ec6eb9dc764b
      - TUYA_DEVICE_ID=eb66bb9aa668e53f31gxsh
      - TUYA_REGION=us
      - RTSP_FRAME_SKIP=2
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - mosquitto
      - go2rtc

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"

  go2rtc:
    image: alexxit/go2rtc:latest
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "1984:1984"
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml
